// // src/api/cart/routes/cart.js

// module.exports = {
//     routes: [
//       // Default routes generated by the CLI
//       {
//         method: 'GET',
//         path: '/carts',
//         handler: 'cart.find',
//         config: {
//           policies: []
//         }
//       },
//       {
//         method: 'GET',
//         path: '/carts/:id',
//         handler: 'cart.findOne',
//         config: {
//           policies: []
//         }
//       },
//       {
//         method: 'POST',
//         path: '/carts',
//         handler: 'cart.create',
//         config: {
//           policies: []
//         }
//       },
//       {
//         method: 'PUT',
//         path: '/carts/:id',
//         handler: 'cart.update',
//         config: {
//           policies: []
//         }
//       },
//       {
//         method: 'DELETE',
//         path: '/carts/:id',
//         handler: 'cart.delete',
//         config: {
//           policies: []
//         }
//       },
      
//       // Custom routes
//       {
//         method: 'GET',
//         path: '/carts/me',
//         handler: 'cart.getMyCart',
//         config: {
//           policies: []
//         }
//       },
//       {
//         method: 'POST',
//         path: '/carts/update',
//         handler: 'cart.updateMyCart',
//         config: {
//           policies: []
//         }
//       }
//     ]
//   };